// Geteilte 18+ Fragendaten – genutzt von Offline-Spielen und Online-Modus

export const WAHRHEIT_18_PLUS: string[] = [
  "Hast du schon mal jemanden geküsst, der/die vergeben war?",
  "Wie viele Personen hast du schon geküsst?",
  "Was ist das Freizügigste, was du je auf einer Party getan hast?",
  "Hast du schon mal jemanden nur wegen Langeweile gedated?",
  "Was ist dein größtes Liebes-Geheimnis?",
  "Hast du schon mal Gefühle für jemanden gehabt, der mit deinem besten Freund zusammen war?",
  "Hast du schon mal jemandem sexts geschickt?",
  "Was ist der heißeste Traum, den du je hattest?",
  "Hast du schon mal aus Mitleid jemanden geküsst?",
  "Hast du schon mal zwei Personen gleichzeitig gedated?",
  "Was ist das Frechste, was du je in einem Chat geschrieben hast?",
  "Mit welcher Person im Raum würdest du am ehesten flirten?",
  "Was ist dein peinlichstes Erlebnis beim Flirten?",
  "Hast du schon mal jemandem eine Lüge über deine Vergangenheit erzählt?",
  "Welche App auf deinem Handy würde dich am meisten blamieren?",
  "Was ist das Aufregendste, was du je getan hast, ohne erwischt zu werden?",
  "Hast du jemals nach einem Treffen sofort bereut, was passiert ist?",
  "Wer hier findest du heimlich am attraktivsten?",
  "Was ist das Wildeste, was du je auf einer Party erlebt hast?",
  "Hast du schon mal jemanden deiner Freunde geküsst?",
  "Hast du schon mal eine Beziehung wegen einer anderen Person beendet?",
  "Was ist die schlimmste sexuelle Situation, in der du je warst?",
  "Was ist der verrückteste Ort, an dem du jemanden geküsst hast?",
  "Hast du schon mal mit jemandem geflirtet, nur um etwas zu bekommen?",
  "Was ist das Schlimmste, was du je getan hast, um einen Ex zurückzugewinnen?",
  "Hast du schon mal jemanden geküsst, wessen Namen du nicht wusstest?",
  "Welches Geheimnis über dein Liebesleben weißt nur du?",
  "Hast du jemals jemanden blockiert und dann entblockt?",
  "Was ist das Aufregendste, was du dir für eine Nacht wünschst?",
  "Hast du schon mal jemandem den Kopf verdreht, ohne es ernst zu meinen?",
  "Was war das Peinlichste, was du je beim Date gesagt hast?",
  "Hast du schon mal jemanden geghostet und warum?",
  "Was ist der größte Schwindel, den du je in einer Beziehung getan hast?",
  "Hast du schon mal mit einem Kollegen oder einer Kollegin geflirtet?",
  "Wer im Raum würde dir am ehesten um 2 Uhr nachts schreiben?",
  "Hast du schon mal deinen eigenen Ex auf einer Party ignoriert?",
  "Was ist die peinlichste Nachricht, die du je abgeschickt hast?",
  "Hast du schon mal jemanden nach Hause eingeladen und dann die Meinung geändert?",
  "Was ist das Schlimmste, was dein Ex je über dich erzählt hat?",
  "Wie lange war deine längste Beziehung, und warum habt ihr euch getrennt?",
  "Hast du schon mal eine Beziehung über WhatsApp beendet?",
  "Hast du schon mal an jemand anderen gedacht, während du jemanden geküsst hast?",
  "Was war dein schlimmstes Date aller Zeiten?",
  "Hast du schon mal jemanden aus Versehen 'Ich liebe dich' gesagt?",
  "Wem im Raum würdest du ein Date vorschlagen, wenn du müsstest?",
  "Was ist die peinlichste Sache, die du je beim Flirten getan hast?",
  "Hast du schon mal jemanden eifersüchtig gemacht – absichtlich?",
  "Hast du schon mal ein Fake-Profil auf einer Dating-App genutzt?",
  "Hast du schon mal jemanden für einen anderen angeschrieben, aus Versehen?",
  "Was war der schlechteste erste Eindruck, den du je gemacht hast?",
  "Was ist das Freizügigste Foto, das du je jemandem geschickt hast?",
  "Hast du schon mal jemanden nur wegen seines Aussehens gedated?",
];

export const PFLICHT_18_PLUS: string[] = [
  "Flüstere der Person neben dir etwas Verführerisches ins Ohr.",
  "Tanze für 30 Sekunden so verführerisch wie möglich.",
  "Sage der Person gegenüber, was dir an ihr physisch am besten gefällt.",
  "Imitiere deinen besten Flirt-Move vor der Gruppe.",
  "Setze dich für 1 Minute auf den Schoß der Person neben dir.",
  "Schick deinem Ex eine Emoji-Nachricht ohne Erklärung.",
  "Gib einer Person im Raum eine 1-minütige Schultermassage.",
  "Küss die Person links von dir auf den Handrücken.",
  "Leg deinen Kopf für 2 Minuten auf den Schoß deines Sitznachbars.",
  "Zeig deinen Lockscreen – wenn da ein Date oder Ex ist, erzähl die Geschichte.",
  "Schreib auf einen Zettel, wen du im Raum küssen würdest, und zeig ihn.",
  "Halte jemandes Hand für 2 Minuten, ohne etwas zu sagen.",
  "Rate, wer im Raum am leidenschaftlichsten küsst. Und begründe es.",
  "Stell dir vor, du bewirbst dich für ein Date mit der Person links von dir. Was sagst du?",
  "Mach einen Liebesbrief in unter 1 Minute an eine Person im Raum.",
  "Beschreibe die Person rechts von dir so attraktiv wie möglich – 30 Sekunden.",
  "Führe mit jemandem ein Fake-Date-Szenario durch – für 2 Minuten.",
  "Wähle einen Songtext, der dein Liebesleben beschreibt. Singe ihn.",
  "Sage jemandem etwas Schmeichelhaftes in deiner verführerischsten Stimme.",
  "Teile dein peinlichstes Dating-App-Gespräch mit der Gruppe.",
  "Sende einer Person im Raum heimlich eine 'Ich mag dich'-Nachricht per Zettel.",
  "Zeig deinen zuletzt gesendeten Text (kein Familienchat).",
  "Ruf eine Person an, auf die du einen Crush hattest, und sag: 'Ich dachte an dich'.",
  "Gib der Person zu deiner Rechten einen Kuss auf die Wange – nur mit deren OK.",
  "Erzähle deinen wildesten Party-Moment in maximal 30 Sekunden.",
  "Mach drei tiefe Augenkontakt-Sekunden mit jeder Person nacheinander.",
  "Schick einer nicht anwesenden Person die Nachricht 'Hey, ich vermisse dich'.",
  "Imitiere, wie du jemanden in einer Bar aufreißen würdest.",
  "Zeig deine Handykontakte und nenne den letzten, mit dem du geflirtet hast.",
  "Tausche für 1 Minute Handy mit der Person zu deiner Linken.",
  "Erzähle die Geschichte deines ersten Kusses.",
  "Beschreibe dein perfektes Date in 20 Sekunden.",
  "Mach für 30 Sekunden die beste Verführer-Stimme und rede irgendetwas.",
  "Schick jemandem im Raum eine Sprachnachricht mit einem Kompliment.",
  "Zeig das peinlichste Foto von dir auf deinem Handy.",
  "Mach 5 Minuten lang den persönlichen Butler der Person links von dir.",
  "Imitiere einen Filmkuss mit einem imaginären Partner.",
  "Sage der Person gegenüber etwas, was du noch nie zu ihr gesagt hast.",
  "Erzähle deinen peinlichsten Moment auf einer Party.",
  "Tue so, als würdest du jemanden aus dem Raum anflirten – für 1 Minute.",
  "Schreib der Person rechts eine Dating-Profil-Beschreibung laut vor.",
  "Nenne 3 Dinge, die du an der Person links von dir attraktiv findest.",
  "Zeig der Gruppe deine Dating-App-Profilfotos.",
  "Erzähle in 30 Sekunden, wie du jemanden in einer Bar ansprechen würdest.",
  "Küss die Hand der Person gegenüber auf dramatische Art.",
  "Wähle jemanden im Raum und sag ihm einen Satz aus einem Liebesfilm.",
  "Zeig, wie du auf Tinder mit jemandem schreiben würdest – und mach es live.",
  "Erzähle das peinlichste Gespräch, das du je mit einem Ex hattest.",
  "Sei für die nächste Runde der/die Chef*in und verteile Trink-Befehle.",
  "Mach für 30 Sekunden die beste Stripclub-Choreografie (angezogen!).",
  "Erzähle deinen heißesten Traum aus der letzten Woche.",
  "Sitz für 1 Runde so nah wie möglich bei der Person, die du am attraktivsten findest.",
];

export const ICH_HAB_NOCH_NIE_18_PLUS: string[] = [
  "jemanden zum ersten Mal getroffen und am selben Abend geküsst.",
  "sexts verschickt oder empfangen.",
  "eine Beziehung wegen einer anderen Person beendet.",
  "eine Beziehung aus Langeweile begonnen.",
  "auf einer Party gemacht, wofür ich mich am nächsten Morgen geschämt habe.",
  "in einem fremden Bett aufgewacht, ohne genau zu wissen, wie ich dahin kam.",
  "jemanden in einer Bar aufgerissen.",
  "absichtlich jemanden eifersüchtig gemacht.",
  "mit meinem Ex geschlafen, nachdem wir uns getrennt hatten.",
  "eine Beziehung verheimlicht.",
  "an jemand anderen gedacht, während ich jemanden geküsst habe.",
  "in einem Flugzeug jemanden kennengelernt und geflirtet.",
  "jemanden geküsst, wessen Namen ich nicht kannte.",
  "eine 'Freunde mit Vorteilen'-Situation gehabt.",
  "jemanden aus Sympathie geküsst, nicht aus Gefühl.",
  "unter dem Tisch Beine berührt, die nicht mir gehörten.",
  "jemanden zuhause angerufen nach einer Partynacht, obwohl es keine gute Idee war.",
  "eine Beziehung durch eine SMS beendet.",
  "gleichzeitig mit zwei Menschen geflirtet.",
  "einen Pool, eine Sauna oder Dusche zu zweit genutzt.",
  "jemanden auf Social Media angeschrieben, dem ich schon lange hinterhergeschaut habe.",
  "absichtlich mein Outfit für jemand Spezielles gewählt.",
  "eine Beziehung im Urlaub gehabt.",
  "jemanden nur wegen seiner Stimme attraktiv gefunden.",
  "auf einem Festival bis zum Morgengrauen mit jemandem Fremdem geredet – und mehr.",
  "meine Nummer gegeben, obwohl ich nicht wollte, dass er anruft.",
  "jemanden geküsst, den ich eigentlich für einen Freund hielt.",
  "in einem Kino geflüstert und dabei mehr getan.",
  "auf einer Hochzeit jemanden angebaggert.",
  "auf Tinder mit jemandem gematcht, den ich kannte, und nichts gesagt.",
  "jemanden gedatet, der/die viel älter oder jünger als ich war.",
  "ein Date abgesagt, um lieber zu Hause zu bleiben.",
  "aus einer WhatsApp-Gruppe ausgetreten, weil mein Ex drin war.",
  "jemanden geblockt und Minuten später wieder entblockt.",
  "meinen Ex auf Social Media gestalkt, nachdem wir uns getrennt hatten.",
  "ein Liebeslied auf jemanden bezogen, der es nie wissen sollte.",
  "jemanden angelogen über mein Alter oder meinen Job beim Dating.",
  "auf einem ersten Date zu viel getrunken.",
  "jemanden nach Hause mitgenommen, den ich erst zwei Stunden kannte.",
  "ein Liebesgeständnis bereut, sobald die Worte raus waren.",
  "einer Person 'Ich liebe dich' gesagt, ohne es wirklich so zu meinen.",
  "mit jemandem geflirtet, nur um ein Getränk zu bekommen.",
  "jemandem eine falsche Handynummer gegeben.",
  "gleichzeitig zwei Dates in einer Woche gehabt.",
  "beim Speed-Dating mitgemacht.",
  "mein Dating-Profil stark übertrieben.",
  "nach einem Streit sofort wieder geküsst.",
  "jemandem heimlich einen Zettel mit meiner Nummer zugesteckt.",
  "jemanden auf einer Party angesprochen, nur weil er/sie so gut aussah.",
  "eine Nacht mit jemandem verbracht, den ich nie wiedersehen sollte.",
  "beim Küssen gegen einen Türrahmen gestoßen.",
  "jemandem eine Liebeserklärung gemacht und keine Antwort bekommen.",
];

export const WER_WUERDE_EHER_18_PLUS: string[] = [
  "auf einer Party mit einer fremden Person nach Hause gehen?",
  "ein Geheimnis preisgeben, nachdem er/sie getrunken hat?",
  "einen One-Night-Stand nicht bereuen?",
  "seinen/ihren Ex um 3 Uhr morgens anrufen?",
  "heimlich jemand anderen attraktiver finden als den eigenen Partner?",
  "eine heimliche Affäre haben?",
  "beim Dating absichtlich lügen?",
  "mit einem Promi flirten und dabei seine Hemmungen verlieren?",
  "auf einer Party im Freien knutschen?",
  "einen Kuss für einen Drink tauschen?",
  "nackt schwimmen gehen, wenn es niemand sieht?",
  "jemanden im Internet ansprechen und ein Date vorschlagen?",
  "auf Tinder alle nach rechts swipen?",
  "eine Beziehung per SMS beenden?",
  "auf einer Hochzeit jemanden aufreißen?",
  "ein Blind Date akzeptieren und danach direkt mehr wollen?",
  "auf einem Festival verschwinden und erst am nächsten Morgen zurückkommen?",
  "seine gesamte Beziehungsgeschichte beim ersten Date erzählen?",
  "jemanden nur anschreiben, um Aufmerksamkeit zu bekommen?",
  "im Flugzeug jemanden kennenlernen und die Nummer nehmen?",
  "beim Speed-Dating mitmachen und alle beeindrucken?",
  "nach dem dritten Date 'Ich liebe dich' sagen?",
  "mit jemandem ausgehen, der/die 10 Jahre älter ist?",
  "den ganzen Abend über seinen/ihren Ex reden?",
  "beim ersten Date zu viel trinken?",
  "das Dating-Profil stark übertreiben?",
  "gleichzeitig mit zwei Personen schreiben?",
  "seinen/ihren Ex auf Social Media stalken?",
  "Strip-Poker spielen und gewinnen?",
  "unter dem Tisch mit jemandem flirten?",
  "eine Wette eingehen, bei der er/sie sich auszieht?",
  "ein heimliches Verhältnis haben?",
  "jemanden nach einer Party einladen, ohne Absichten zu haben – und sie dann doch zu haben?",
  "auf einer Party einschlafen und nicht merken, was passiert?",
  "eine Beziehung nur wegen Äußerlichkeiten beginnen?",
  "beim ersten Kuss die falsche Richtung wählen?",
  "auf Social Media eine romantische Liebeserklärung posten?",
  "bei einer Gruppenreise ein Doppelzimmer teilen wollen?",
  "absichtlich jemanden eifersüchtig machen?",
  "nach einem schlechten Date sofort das nächste planen?",
  "jemanden ghosten, nur weil er/sie zu viel schreibt?",
  "in einer Bar jemanden mit einer schlechten Pickup-Line ansprechen?",
  "auf einem ersten Date ein Foto machen und auf Instagram posten?",
  "spontan über Nacht bei jemandem bleiben, den er/sie gerade erst kennengelernt hat?",
  "auf einer Party die meisten Nummern einsammeln?",
  "jemanden schon beim ersten Treffen küssen?",
  "auf einem Date das Handy nicht aus der Hand legen können?",
  "heimlich einen Crush auf jemanden im Raum haben?",
  "jemanden nach Hause einladen und dann die Meinung ändern?",
  "beim nächsten Singleurlaub eine Affäre haben?",
  "jemanden daten, der/die einen Freund/eine Freundin kennt?",
  "nach einem Streit direkt wieder anfangen zu flirten?",
  "jemandem beim ersten Date zu viel über seinen Ex erzählen?",
];
